-- MySQL Script generated by MySQL Workbench
-- Wed Oct 19 00:01:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema herosightingdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema herosightingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `herosightingdb` DEFAULT CHARACTER SET utf8 ;
USE `herosightingdb` ;

-- -----------------------------------------------------
-- Table `herosightingdb`.`Hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herosightingdb`.`Hero` (
  `idHero` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `superpower` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idHero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `herosightingdb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herosightingdb`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `latitude` DECIMAL(10,8) NULL,
  `longitude` DECIMAL(11,8) NULL,
  PRIMARY KEY (`idLocation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `herosightingdb`.`Sighting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herosightingdb`.`Sighting` (
  `idHero` INT NOT NULL,
  `idLocation` INT NOT NULL,
  `date` DATE NOT NULL,
  `idSighting` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idSighting`),
  INDEX `fk_Hero_has_Location_Location1_idx` (`idLocation` ASC) VISIBLE,
  INDEX `fk_Hero_has_Location_Hero1_idx` (`idHero` ASC) VISIBLE,
  CONSTRAINT `fk_Hero_has_Location_Hero1`
    FOREIGN KEY (`idHero`)
    REFERENCES `herosightingdb`.`Hero` (`idHero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hero_has_Location_Location1`
    FOREIGN KEY (`idLocation`)
    REFERENCES `herosightingdb`.`Location` (`idLocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `herosightingdb`.`Organisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herosightingdb`.`Organisation` (
  `idOrganisation` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `contact` VARCHAR(50) NULL,
  PRIMARY KEY (`idOrganisation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `herosightingdb`.`HeroOrganisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `herosightingdb`.`HeroOrganisation` (
  `idOrganisation` INT NOT NULL,
  `idHero` INT NOT NULL,
  PRIMARY KEY (`idOrganisation`, `idHero`),
  INDEX `fk_Organisation_has_Hero_Hero1_idx` (`idHero` ASC) VISIBLE,
  INDEX `fk_Organisation_has_Hero_Organisation1_idx` (`idOrganisation` ASC) VISIBLE,
  CONSTRAINT `fk_Organisation_has_Hero_Organisation1`
    FOREIGN KEY (`idOrganisation`)
    REFERENCES `herosightingdb`.`Organisation` (`idOrganisation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Organisation_has_Hero_Hero1`
    FOREIGN KEY (`idHero`)
    REFERENCES `herosightingdb`.`Hero` (`idHero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
